In [1]:
import tika
from tika import parser
import pandas as pd
from pandas import read_excel
import openpyxl
import re

In [2]:
#read BIK
bik=pd.read_csv('updated_bik.csv')
bik

,Unnamed: 0,Authors,Title,Citation,DOI,Year,Month,0,1,2,...,Correction,No Action,SUM \nCompleted,affiliation,lab_size,Highest_degree,Degree_area,Publication Rate,Other Journals Published In,duration of Career(Years)
0,0,"Inka Regine Weingaertner, Sarah Koutnik, Herma...",Rounak Nassirpour,"PLOS One, January 2013 | Volume 8 | Issue 1 | ...",10.1371/journal.pone.0053510,2013,1-Jan,1.0,NaN,1.0,...,1.0,NaN,1,"Institute of Pharmacology, Toxicology and Phar...",3,NaN,NaN,1.000000,3,3
1,1,"Jessica M. Esparza, Eileen OÅToole, Linya Li,...",Katanin Localization Requires Triplet Microtub...,"PLOS ONE, January 2013 | Volume 8 | Issue 1 | ...",10.1371/journal.pone.0053940,2013,1-Jan,NaN,1.0,NaN,...,1.0,NaN,1,"Department of Genetics, Washington University ...",7,NaN,NaN,0.454545,5,11
2,2,"Sreedevi Avasarala, Fangfang Zhang, Guangliang...",Curcumin Modulates the Inflammatory Response a...,"PLOS ONE, February 2013 | Volume 8 | Issue 2 |...",10.1371/journal.pone.0057285,2013,2-Feb,NaN,NaN,1.0,...,1.0,NaN,1,"Department of Oral Biology and Pathology, Scho...",6,NaN,NaN,2.000000,16,8
3,3,"Rounak Nassirpour, Pramod P. Mehta, Sangita M....",miR-221 Promotes Tumorigenesis in Human Triple...,"PLOS ONE, April 2013 | Volume 8 | Issue 4 | e6...",10.1371/journal.pone.0062170,2013,04April,1.0,NaN,NaN,...,NaN,NaN,1,"Oncology Research, Pfizer Worldwide Research a...",4,NaN,NaN,0.789474,15,19
4,4,"Jianuo Liu, Peng Xu, Cory Collins, Han Liu, J...",HIV-1 Tat Protein Increases Microglial Outward...,"PLOS ONE, May 2013 | Volume 8 | Issue 5 | e649...",10.1371/journal.pone.0064904,2013,5-May,NaN,1.0,NaN,...,1.0,NaN,1,"Neurophysiology Laboratory, Department of Phar...",7,NaN,NaN,2.857143,40,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,209,"Nathalie Delgehyr, Uta Wieland, He_lÅ¹ne Rango...","Drosophila Mgr, a Prefoldin subunit cooperatin...","PNAS | April 10, 2012 | vol. 109 | no. 15 | 57...",10.1073/pnas.1108537109,2012,NaN,NaN,1.0,NaN,...,1.0,NaN,1,"Department of Genetics, Cancer Research United...",25,NaN,NaN,1.300000,13,10
210,210,"Rajesh K. Grover, Julong Cheng, Yingjie Peng, ...",The costimulatory immunogen LPS induces the B-...,"PNAS _ April 17, 2012 _ vol. 109 _ no. 16, 603...",10.1073/pnas.1202214109,2012,NaN,NaN,1.0,NaN,...,1.0,NaN,1,"Departments of Molecular Biology, The Scripps ...",21,NaN,NaN,2.312500,37,16
211,211,"Kevin Y. Lee, Yuji Yamamoto, Jeremie Boucher, ...",Shox2 is a molecular determinant of depot-spec...,"PNAS | July 9, 2013 | vol. 110 | no. 28 | 1140...",10.1073/pnas.1310331110,2013,NaN,NaN,1.0,NaN,...,1.0,NaN,1,Section on Integrative Physiology and Metaboli...,17,PhD,NaN,2.882353,49,17
212,212,"Shuyu Ren, Bryce G. Johnson, Yujiro Kida, Coli...",LRP-6 is a coreceptor for multiple fibrogenic ...,"PNAS | January22,2013 | vol.110 | no.4 | 1441",10.1073/pnas.1211179110,2013,NaN,NaN,NaN,1.0,...,1.0,NaN,1,Division of Nephrology and Center for Lung Bio...,23,NaN,NaN,3.600000,36,10
213,213,"Zhongyuan Wang, Yanping Wu, Haifeng Wang, Yang...",Interplay of mevalonate and Hippo pathways reg...,"PNAS | Published online December 23, 2013 | E8...",10.1073/pnas.1319190110,2014,NaN,NaN,NaN,1.0,...,1.0,NaN,1,"School of Life Sciences, Tsinghua University, ...",31,NaN,NaN,63.500000,127,2

In [4]:
#read dataset1
dataset1=pd.read_excel('3datasets/dataset1/NSF-metadata.xlsx',engine='openpyxl')
dataset1

/Users/apple/opt/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,NSF-PAR ID,DOI,Title,Creator/Author,Editor,Publication Date,Journal Name,Journal Volume,Journal Issue,Page Range or eLocation,...,Description/Abstract,Sponsoring Org.,Award IDs,Subject,Publication Year,Size,Format,Version,Resource Type,Publisher
0,10327919,https://doi.org/10.1186/s41235-022-00388-4,Effects of experience on recognition of speech...,"Crinnion, Anne Marie; Toscano, Joseph C.; Tosc...",NaN,2022-12-01T05:00:00Z,Cognitive Research: Principles and Implications,7,1,NaN,...,"Abstract Over the past two years, f...",National Science Foundation,1945069,NaN,2022,NaN,NaN,NaN,Publication,NaN
1,10323229,https://doi.org/10.1007/s40656-022-00497-9,Re-situations of scientific knowledge: a case ...,"Griesemer, James; Barragán, Carlos Andrés",NaN,2022-06-01T04:00:00Z,History and Philosophy of the Life Sciences,44,2,NaN,...,Abstract We track and...,National Science Foundation,1849307,NaN,2022,NaN,NaN,NaN,Publication,NaN
2,10327937,https://doi.org/10.5281/zenodo.6540831,Ixodes Scapularis monitoring data compiled fro...,"Christie, Rowan; Stack, Kaitlin Whitney; Perro...",NaN,2022-01-01T05:00:00Z,NaN,NaN,NaN,NaN,...,"{""Abstract"":[""<p>This dataset lists 289 blackl...",National Science Foundation,1838807,NaN,2022,NaN,NaN,NaN,Dataset,Zenodo
3,10289609,https://doi.org/10.3389/fmolb.2021.618068,Role of Electrostatic Hotspots in the Selectiv...,"Narkhede, Yogesh B.; Gautam, Avneesh K.; Hsu, ...",NaN,2021-03-16T04:00:00Z,Frontiers in Molecular Biosciences,8,NaN,NaN,...,"Poxviruses are dangerous pathogens, which can ...",National Science Foundation,1905374,NaN,2021,NaN,NaN,NaN,Publication,NaN
4,10099205,https://doi.org/1006549,"G Hartung, C Vesel, R Morley**, A Alaraj, J Sl...","Grant Hartung, Claudia Vesel",NaN,2018-11-19T05:00:00Z,PLOS computational biology,14,11,1-25,...,Recent advances in modeling oxygen supply to c...,National Science Foundation,1706921,NaN,2018,1-25,NaN,NaN,Publication,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,10042626,https://doi.org/10.3354/meps12253,Mass mortality of marine birds in the Northeas...,"Jones, T; Parrish, JK; Punt, AE; Trainer, VL; ...",NaN,2017-09-14T04:00:00Z,Marine Ecology Progress Series,579,NaN,111 to 127,...,NaN,National Science Foundation,1649210,NaN,2017,111 to 127,NaN,NaN,Publication,NaN
1996,10072502,https://doi.org/https://doi.org/10.3390/met711...,The Biological Responses to Magnesium-Based Bi...,"Lumei Liu, Juan Wang",NaN,2017-11-17T05:00:00Z,Metals,7,11,514,...,The biocompatibility of Magnesium-based materi...,National Science Foundation,1649243,NaN,2017,514,NaN,NaN,Publication,NaN
1997,10062069,https://doi.org/10.1016/j.ympev.2018.03.015,Diversity within diversity: Parasite species r...,"Santos, Juan C.; Tarvin, Rebecca D.; O'Connell...",NaN,2018-08-01T04:00:00Z,Molecular Phylogenetics and Evolution,125,C,40 to 50,...,NaN,National Science Foundation,1556967,NaN,2018,40 to 50,NaN,NaN,Publication,NaN
1998,10076918,https://doi.org/10.1029/2018GL078837,Similarity in Fog and Rainfall Intermittency,"Räsänen, M. [Institute for Atmospheric and Ear...",NaN,2018-10-07T04:00:00Z,Geophysical Research Letters,45,19,"p. 10,691-10,699",...,Not Available,National Science Foundation,1644382; 1754893,NaN,2018,"p. 10,691-10,699",NaN,NaN,Publication,DOI PREFIX: 10.1029
1999,10087941,https://doi.org/10.23919/EUSIPCO.2018.8553229,Blind Identification of Invertible Graph Filte...,"Ye, Chang; Shafipour, Rasoul; Mateos, Gonzalo",NaN,2018-09-01T04:00:00Z,2018 26th European Signal Processing Conferenc...,NaN,NaN,121 to 125,...,This paper deals with the problem of blind ide...,National Science Foundation,1809356,NaN,2018,121 to 125,NaN,NaN,Publication,NaN

In [5]:
#extracting features: DOI,Title,Creator/Author,Journal Name,Sponsoring Org.
dataset_1_new=dataset1.loc[:,['DOI','Title','Creator/Author','Journal Name','Sponsoring Org.']]
dataset_1_new

,DOI,Title,Creator/Author,Journal Name,Sponsoring Org.
0,https://doi.org/10.1186/s41235-022-00388-4,Effects of experience on recognition of speech...,"Crinnion, Anne Marie; Toscano, Joseph C.; Tosc...",Cognitive Research: Principles and Implications,National Science Foundation
1,https://doi.org/10.1007/s40656-022-00497-9,Re-situations of scientific knowledge: a case ...,"Griesemer, James; Barragán, Carlos Andrés",History and Philosophy of the Life Sciences,National Science Foundation
2,https://doi.org/10.5281/zenodo.6540831,Ixodes Scapularis monitoring data compiled fro...,"Christie, Rowan; Stack, Kaitlin Whitney; Perro...",NaN,National Science Foundation
3,https://doi.org/10.3389/fmolb.2021.618068,Role of Electrostatic Hotspots in the Selectiv...,"Narkhede, Yogesh B.; Gautam, Avneesh K.; Hsu, ...",Frontiers in Molecular Biosciences,National Science Foundation
4,https://doi.org/1006549,"G Hartung, C Vesel, R Morley**, A Alaraj, J Sl...","Grant Hartung, Claudia Vesel",PLOS computational biology,National Science Foundation
...,...,...,...,...,...
1995,https://doi.org/10.3354/meps12253,Mass mortality of marine birds in the Northeas...,"Jones, T; Parrish, JK; Punt, AE; Trainer, VL; ...",Marine Ecology Progress Series,National Science Foundation
1996,https://doi.org/https://doi.org/10.3390/met711...,The Biological Responses to Magnesium-Based Bi...,"Lumei Liu, Juan Wang",Metals,National Science Foundation
1997,https://doi.org/10.1016/j.ympev.2018.03.015,Diversity within diversity: Parasite species r...,"Santos, Juan C.; Tarvin, Rebecca D.; O'Connell...",Molecular Phylogenetics and Evolution,National Science Foundation
1998,https://doi.org/10.1029/2018GL078837,Similarity in Fog and Rainfall Intermittency,"Räsänen, M. [Institute for Atmospheric and Ear...",Geophysical Research Letters,National Science Foundation
1999,https://doi.org/10.23919/EUSIPCO.2018.8553229,Blind Identification of Invertible Graph Filte...,"Ye, Chang; Shafipour, Rasoul; Mateos, Gonzalo",2018 26th European Signal Processing Conferenc...,National Science Foundation

In [6]:
#read dataset2
dataset_2=pd.read_csv('3datasets/dataset2/Colleges_and_Universities.csv')
dataset_2

,X,Y,OBJECTID,IPEDSID,NAME,ADDRESS,CITY,STATE,ZIP,ZIP4,...,ALIAS,SIZE_SET,INST_SIZE,PT_ENROLL,FT_ENROLL,TOT_ENROLL,HOUSING,DORM_CAP,TOT_EMP,SHELTER_ID
0,-8.765605e+06,5.318192e+06,1,189556,BRYANT & STRATTON COLLEGE-AMHERST,3650 MILLERSPORT HIGHWAY,GETZVILLE,NY,14068,NOT AVAILABLE,...,NOT AVAILABLE,6,-2,-999,-999,-999,-1,-999,-999,NOT AVAILABLE
1,-8.231383e+06,4.975222e+06,2,190682,CUNY SCHOOL OF LAW,2 COURT SQUARE,LONG ISLAND CITY,NY,11101,NOT AVAILABLE,...,LAW SCHOOL | CUNY LAW SCHOOL,18,1,192,434,626,2,-999,233,NOT AVAILABLE
2,-8.247285e+06,5.032103e+06,3,195058,ROCKLAND COMMUNITY COLLEGE,145 COLLEGE RD,SUFFERN,NY,10901,3699,...,NOT AVAILABLE,3,3,3207,3325,6532,2,-999,923,NOT AVAILABLE
3,-8.208890e+06,5.008471e+06,4,193122,SOUTHERN WESTCHESTER BOCES-PRACTICAL NURSING P...,450 MAMARONECK AVENUE,HARRISON,NY,10528,NOT AVAILABLE,...,NOT AVAILABLE,-2,1,22,31,53,2,-999,24,NOT AVAILABLE
4,-8.969252e+06,4.965197e+06,5,204884,OHIO VALLEY COLLEGE OF TECHNOLOGY,15258 STATE ROUTE 170,EAST LIVERPOOL,OH,43920,9585,...,NOT AVAILABLE,1,1,24,165,189,2,-999,38,NOT AVAILABLE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6554,-9.317151e+06,5.308190e+06,6555,494889,BAKER COLLEGE - FLINT,1050 WEST BRISTOL ROAD,FLINT,MI,48507,5508,...,NOT AVAILABLE,-2,-2,-999,-999,-999,-1,-999,-999,NOT AVAILABLE
6555,-1.082780e+07,4.536689e+06,6556,494898,WELLSPRING SCHOOL OF ALLIED HEALTH-WICHITA,"650 N CARRIAGE PARKWAY, STE 55",WICHITA,KS,67208,4501,...,NOT AVAILABLE,-2,1,-999,38,38,2,-999,14,NOT AVAILABLE
6556,-8.145887e+06,4.983035e+06,6557,494904,ACCESS CAREERS-ISLANDIA,"1930 VETERANS HIGHWAY, SUITE 10",ISLANDIA,NY,11749,1599,...,NOT AVAILABLE,-2,1,43,20,63,2,-999,18,NOT AVAILABLE
6557,-1.304572e+07,3.865065e+06,6558,494913,FRANCISCAN SCHOOL OF THEOLOGY - SAN DIEGO,5998 ALCALA PARK,SAN DIEGO,CA,92110,2492,...,NOT AVAILABLE,-2,-2,-999,-999,-999,-1,-999,-999,NOT AVAILABLE
6558,-1.270918e+07,5.819852e+06,6559,494922,UNIVERSITY OF MONTANA (THE) - BITTERROOT COLLE...,103 SOUTH 9TH STREET,HAMILTON,MT,59840,3213,...,NOT AVAILABLE,-2,-2,-999,-999,-999,-1,-999,-999,NOT AVAILABLE

In [7]:
#extracting features: NAME,ADDRESS,STATE,COUNTRY,COUNTY,SOURCE,WEBSITE
dataset_2_new=dataset_2.loc[:,['NAME','ADDRESS','STATE','COUNTRY','COUNTY','SOURCE','WEBSITE']]
dataset_2_new

,NAME,ADDRESS,STATE,COUNTRY,COUNTY,SOURCE,WEBSITE
0,BRYANT & STRATTON COLLEGE-AMHERST,3650 MILLERSPORT HIGHWAY,NY,USA,ERIE,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,https://www.bryantstratton.edu
1,CUNY SCHOOL OF LAW,2 COURT SQUARE,NY,USA,QUEENS,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.law.cuny.edu
2,ROCKLAND COMMUNITY COLLEGE,145 COLLEGE RD,NY,USA,ROCKLAND,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.sunyrockland.edu/
3,SOUTHERN WESTCHESTER BOCES-PRACTICAL NURSING P...,450 MAMARONECK AVENUE,NY,USA,WESTCHESTER,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.swboces.org
4,OHIO VALLEY COLLEGE OF TECHNOLOGY,15258 STATE ROUTE 170,OH,USA,COLUMBIANA,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,ovct.edu
...,...,...,...,...,...,...,...
6554,BAKER COLLEGE - FLINT,1050 WEST BRISTOL ROAD,MI,USA,GENESEE,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,NOT AVAILABLE
6555,WELLSPRING SCHOOL OF ALLIED HEALTH-WICHITA,"650 N CARRIAGE PARKWAY, STE 55",KS,USA,SEDGWICK,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.wellspring.edu
6556,ACCESS CAREERS-ISLANDIA,"1930 VETERANS HIGHWAY, SUITE 10",NY,USA,SUFFOLK,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.accesscareers.net
6557,FRANCISCAN SCHOOL OF THEOLOGY - SAN DIEGO,5998 ALCALA PARK,CA,USA,SAN DIEGO,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,NOT AVAILABLE
6558,UNIVERSITY OF MONTANA (THE) - BITTERROOT COLLE...,103 SOUTH 9TH STREET,MT,USA,RAVALLI,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,NOT AVAILABLE

In [9]:
#read dataset3
f=open("3datasets/dataset3/QSrank.txt")
line = f.readline()
columns=[]
while line:
    columns.append(line.rstrip('\n'))
    line = f.readline()
columns

['1         Massachusetts Institute of Technology (MIT)                                            North America                                      100',
 '2         Stanford University                                                                    North America                                      98.6',
 '3         Harvard University                                                                     North America                                      98.5',
 '4         California Institute of Technology (Caltech)                                           North America                                      97.2',
 '5         University of Oxford                                                                       Europe                                         96.8',
 '6         University of Cambridge                                                                    Europe                                         95.6',
 '7         ETH Zurich - Swiss Federal Institute of Technology                                         Europe                                         95.3',
 '8         Imperial College London                                                                    Europe                                         93.3',
 '9         University of Chicago                                                                  North America                                      93.2',
 '10        UCL (University College London)                                                            Europe                                         92.9',
 '11        National University of Singapore (NUS)                                                      Asia                                          92',
 '12        Nanyang Technological University, Singapore (NTU)                                           Asia                                          91.3',
 '13        Princeton University                                                                   North America                                      90.9',
 '14        Cornell University                                                                     North America                                      90.5',
 '15        Yale University                                                                        North America                                      89.6',
 '16        Columbia University                                                                    North America                                      88.5',
 '17        Tsinghua University                                                                         Asia                                          87.2',
 '18        The University of Edinburgh                                                                Europe                                         86.9',
 '19        University of Pennsylvania                                                             North America                                      86.5',
 '20        University of Michigan                                                                 North America                                      86.4',
 '21        Johns Hopkins University                                                               North America                                      85.9',
 '22        EPFL - Ecole Polytechnique Federale de Lausanne                                            Europe                                         85.8',
 '23        The University of Tokyo                                                                     Asia                                          85.3',
 '24        The Australian National University                                                        Oceania                                         84.4',
 '25        The University of Hong Kong                                                                 Asia                                          84.3',
 '26        Duke University                                                                        North America                                      83.9',
 '27        University of California, Berkeley (UCB)                                               North America                                      83.2',
 '28        University of Toronto                                                                  North America                                      83',
 '29        The University of Manchester                                                               Europe                                         82.9',
 '30        Peking University                                                                           Asia                                          82.6',
 "31        King's College London                                                                      Europe                                         82.5",
 '32        University of California, Los Angeles (UCLA)                                           North America                                      81.9',
 '33        McGill University                                                                      North America                                      81.7',
 '34        Northwestern University                                                                North America                                      81.5',
 '35        Kyoto University                                                                            Asia                                          81.2',
 '36        Seoul National University                                                                   Asia                                          80.6',
 '37        The Hong Kong University of Science and Technology                                          Asia                                          80.5',
 '38        London School of Economics and Political Science (LSE)                                         Europe                                         80.2',
 '39        The University of Melbourne                                                               Oceania                                         80.1',
 '40        KAIST - Korea Advanced Institute of Science & Technology                                          Asia                                          78.7',
 '41        University of California, San Diego (UCSD)                                             North America                                      78.6',
 '42        The University of Sydney                                                                  Oceania                                         78.3',
 '43        New York University (NYU)                                                              North America                                      77.7',
 '44        Fudan University                                                                            Asia                                          77.6',
 '45        The University of New South Wales (UNSW Sydney)                                           Oceania                                         77',
 '46        Carnegie Mellon University                                                             North America                                      76.6',
 '47        University of British Columbia                                                         North America                                      75.8',
 '48        The University of Queensland                                                              Oceania                                         75.7',
 '49        The Chinese University of Hong Kong (CUHK)                                                  Asia                                          75.6',
 '50        Université PSL                                                                             Europe                                         75.1',
 '51        University of Bristol                                                                      Europe                                         74.9',
 '52        Delft University of Technology                                                             Europe                                         73.3',
 '53        University of Wisconsin-Madison                                                        North America                                      73.2',
 '54        The University of Warwick                                                                  Europe                                         72.9',
 '55        City University of Hong Kong                                                                Asia                                          72.1',
 '56        Brown University                                                                       North America                                      72',
 '57        University of Amsterdam                                                                    Europe                                         71.1',
 '58        Tokyo Institute of Technology                                                               Asia                                          71',
 '59        Monash University                                                                         Oceania                                         70.4',
 '59        Shanghai Jiao Tong University                                                               Asia                                          70.4',
 '61        Technical University of Munich                                                             Europe                                         70',
 '62        Ludwig-Maximilians-Universität München                                                     Europe                                         69.4',
 '63        University of Texas at Austin                                                          North America                                      68.7',
 '64        Ruprecht-Karls-Universität Heidelberg                                                      Europe                                         68',
 '65        Ecole Polytechnique                                                                        Europe                                         67.9',
 '66        University of Washington                                                               North America                                      67.8',
 '67        Osaka University                                                                            Asia                                          67.7',
 '68        Zhejiang University                                                                         Asia                                          67.5',
 '69        Georgia Institute of Technology                                                        North America                                      67.4',
 '69        University of Glasgow                                                                      Europe                                         67.4',
 '71        University of Illinois at Urbana-Champaign                                             North America                                      67',
 '72        National Taiwan University (NTU)                                                            Asia                                          66.3',
 '73        Universidad de Buenos Aires (UBA)                                                      Latin America                                      66.2',
 '74        Durham University                                                                          Europe                                         65.7',
 '75        Sorbonne University                                                                        Europe                                         64.8',
 '75        The University of Sheffield                                                                Europe                                         64.8',
 '77        Tohoku University                                                                           Asia                                          64.3',
 '78        University of Zurich                                                                       Europe                                         63.6',
 '79        University of Birmingham                                                                   Europe                                         63.5',
 '79        University of Copenhagen                                                                   Europe                                         63.5',
 '81        KU Leuven                                                                                  Europe                                         63.4',
 '82        University of Nottingham                                                                   Europe                                         63.1',
 '83        Pohang University of Science And Technology (POSTECH)                                          Asia                                          63',
 '83        University of North Carolina, Chapel Hill                                              North America                                      63',
 '85        The University of Auckland                                                                Oceania                                         62.8',
 '86        Korea University                                                                            Asia                                          62.7',
 '87        Rice University                                                                        North America                                      62.6',
 '87        Universiti Malaya (UM)                                                                      Asia                                          62.6',
 '89        The Ohio State University                                                              North America                                      62.4',
 '90        Lomonosov Moscow State University                                                          Europe                                         62.3',
 '91        The University of Western Australia                                                       Oceania                                         62.2',
 '92        Lund University                                                                            Europe                                         62.1',
 '93        Boston University                                                                      North America                                      62',
 '93        University of Leeds                                                                        Europe                                         62',
 '95        Pennsylvania State University                                                          North America                                      61.9',
 '96        University of Southampton                                                                  Europe                                         61.6',
 '97        University of St Andrews                                                                   Europe                                         61.4',
 '98        University of Science and Technology of China                                               Asia                                          60.8',
 '99        Eindhoven University of Technology                                                         Europe                                         59.8',
 '100       Purdue University                                                                      North America                                      59.5',
 '100       Sungkyunkwan University (SKKU)                                                              Asia                                          59.5',
 '100       University of California, Davis                                                        North America                                      59.5',
 '100       Washington University in St. Louis                                                     North America                                      59.5',
 '104       KTH Royal Institute of Technology                                                          Europe                                         59.3',
 '104       Trinity College Dublin, The University of Dublin                                           Europe                                         59.3',
 '106       The Hong Kong Polytechnic University                                                        Asia                                          59.1',
 '107       Yonsei University                                                                           Asia                                          58.9',
 '108       University of Geneva                                                                       Europe                                         58.4',
 '109       University of Alberta                                                                  North America                                      58.1',
 '110       University of Helsinki                                                                     Europe                                         57.9',
 '111       Nagoya University                                                                           Asia                                          57.3',
 '112       Technical University of Denmark                                                            Europe                                         57.1',
 '113       Universidad Nacional Autónoma de México  (UNAM)                                        Latin America                                      56.8',
 '114       The University of Adelaide                                                                Oceania                                         56.6',
 '115       University of Southern California                                                      North America                                      56.2',
 '116       KIT, Karlsruhe Institute of Technology                                                     Europe                                         55.9',
 '117       Uppsala University                                                                         Europe                                         55.8',
 '118       Universidade de São Paulo                                                              Latin America                                      55.5',
 '119       Queen Mary University of London                                                            Europe                                         55.4',
 '120       University of Groningen                                                                    Europe                                         55.2',
 '121       Humboldt-Universität zu Berlin                                                             Europe                                         55.1',
 '122       Leiden University                                                                          Europe                                         55',
 '122       Nanjing University                                                                          Asia                                          55',
 '124       Utrecht University                                                                         Europe                                         54.5',
 '125       Wageningen University                                                                      Europe                                         54.4',
 '126       Kyushu University                                                                           Asia                                          54.1',
 '126       University of Maryland, College Park                                                   North America                                      54.1',

In [10]:
#split 
all_data_3=[]
for i in range(len(columns)):
    chunks = re.split('  +', columns[i])
    all_data_3.append(chunks)
print(all_data_3)

[['1', 'Massachusetts Institute of Technology (MIT)', 'North America', '100'], ['2', 'Stanford University', 'North America', '98.6'], ['3', 'Harvard University', 'North America', '98.5'], ['4', 'California Institute of Technology (Caltech)', 'North America', '97.2'], ['5', 'University of Oxford', 'Europe', '96.8'], ['6', 'University of Cambridge', 'Europe', '95.6'], ['7', 'ETH Zurich - Swiss Federal Institute of Technology', 'Europe', '95.3'], ['8', 'Imperial College London', 'Europe', '93.3'], ['9', 'University of Chicago', 'North America', '93.2'], ['10', 'UCL (University College London)', 'Europe', '92.9'], ['11', 'National University of Singapore (NUS)', 'Asia', '92'], ['12', 'Nanyang Technological University, Singapore (NTU)', 'Asia', '91.3'], ['13', 'Princeton University', 'North America', '90.9'], ['14', 'Cornell University', 'North America', '90.5'], ['15', 'Yale University', 'North America', '89.6'], ['16', 'Columbia University', 'North America', '88.5'], ['17', 'Tsinghua University', 'Asia', '87.2'], ['18', 'The University of Edinburgh', 'Europe', '86.9'], ['19', 'University of Pennsylvania', 'North America', '86.5'], ['20', 'University of Michigan', 'North America', '86.4'], ['21', 'Johns Hopkins University', 'North America', '85.9'], ['22', 'EPFL - Ecole Polytechnique Federale de Lausanne', 'Europe', '85.8'], ['23', 'The University of Tokyo', 'Asia', '85.3'], ['24', 'The Australian National University', 'Oceania', '84.4'], ['25', 'The University of Hong Kong', 'Asia', '84.3'], ['26', 'Duke University', 'North America', '83.9'], ['27', 'University of California, Berkeley (UCB)', 'North America', '83.2'], ['28', 'University of Toronto', 'North America', '83'], ['29', 'The University of Manchester', 'Europe', '82.9'], ['30', 'Peking University', 'Asia', '82.6'], ['31', "King's College London", 'Europe', '82.5'], ['32', 'University of California, Los Angeles (UCLA)', 'North America', '81.9'], ['33', 'McGill University', 'North America', '81.7'], ['34', 'Northwestern University', 'North America', '81.5'], ['35', 'Kyoto University', 'Asia', '81.2'], ['36', 'Seoul National University', 'Asia', '80.6'], ['37', 'The Hong Kong University of Science and Technology', 'Asia', '80.5'], ['38', 'London School of Economics and Political Science (LSE)', 'Europe', '80.2'], ['39', 'The University of Melbourne', 'Oceania', '80.1'], ['40', 'KAIST - Korea Advanced Institute of Science & Technology', 'Asia', '78.7'], ['41', 'University of California, San Diego (UCSD)', 'North America', '78.6'], ['42', 'The University of Sydney', 'Oceania', '78.3'], ['43', 'New York University (NYU)', 'North America', '77.7'], ['44', 'Fudan University', 'Asia', '77.6'], ['45', 'The University of New South Wales (UNSW Sydney)', 'Oceania', '77'], ['46', 'Carnegie Mellon University', 'North America', '76.6'], ['47', 'University of British Columbia', 'North America', '75.8'], ['48', 'The University of Queensland', 'Oceania', '75.7'], ['49', 'The Chinese University of Hong Kong (CUHK)', 'Asia', '75.6'], ['50', 'Université PSL', 'Europe', '75.1'], ['51', 'University of Bristol', 'Europe', '74.9'], ['52', 'Delft University of Technology', 'Europe', '73.3'], ['53', 'University of Wisconsin-Madison', 'North America', '73.2'], ['54', 'The University of Warwick', 'Europe', '72.9'], ['55', 'City University of Hong Kong', 'Asia', '72.1'], ['56', 'Brown University', 'North America', '72'], ['57', 'University of Amsterdam', 'Europe', '71.1'], ['58', 'Tokyo Institute of Technology', 'Asia', '71'], ['59', 'Monash University', 'Oceania', '70.4'], ['59', 'Shanghai Jiao Tong University', 'Asia', '70.4'], ['61', 'Technical University of Munich', 'Europe', '70'], ['62', 'Ludwig-Maximilians-Universität München', 'Europe', '69.4'], ['63', 'University of Texas at Austin', 'North America', '68.7'], ['64', 'Ruprecht-Karls-Universität Heidelberg', 'Europe', '68'], ['65', 'Ecole Polytechnique', 'Europe', '67.9'], ['66', 'University of Washington', 'North America', '67.8'], ['67', 'Osaka University', 'Asia', '67.7'], ['68', 'Zhejiang University', 'Asia', '67.5'], ['69', 'Georgia Institute of Technology', 'North America', '67.4'], ['69', 'University of Glasgow', 'Europe', '67.4'], ['71', 'University of Illinois at Urbana-Champaign', 'North America', '67'], ['72', 'National Taiwan University (NTU)', 'Asia', '66.3'], ['73', 'Universidad de Buenos Aires (UBA)', 'Latin America', '66.2'], ['74', 'Durham University', 'Europe', '65.7'], ['75', 'Sorbonne University', 'Europe', '64.8'], ['75', 'The University of Sheffield', 'Europe', '64.8'], ['77', 'Tohoku University', 'Asia', '64.3'], ['78', 'University of Zurich', 'Europe', '63.6'], ['79', 'University of Birmingham', 'Europe', '63.5'], ['79', 'University of Copenhagen', 'Europe', '63.5'], ['81', 'KU Leuven', 'Europe', '63.4'], ['82', 'University of Nottingham', 'Europe', '63.1'], ['83', 'Pohang University of Science And Technology (POSTECH)', 'Asia', '63'], ['83', 'University of North Carolina, Chapel Hill', 'North America', '63'], ['85', 'The University of Auckland', 'Oceania', '62.8'], ['86', 'Korea University', 'Asia', '62.7'], ['87', 'Rice University', 'North America', '62.6'], ['87', 'Universiti Malaya (UM)', 'Asia', '62.6'], ['89', 'The Ohio State University', 'North America', '62.4'], ['90', 'Lomonosov Moscow State University', 'Europe', '62.3'], ['91', 'The University of Western Australia', 'Oceania', '62.2'], ['92', 'Lund University', 'Europe', '62.1'], ['93', 'Boston University', 'North America', '62'], ['93', 'University of Leeds', 'Europe', '62'], ['95', 'Pennsylvania State University', 'North America', '61.9'], ['96', 'University of Southampton', 'Europe', '61.6'], ['97', 'University of St Andrews', 'Europe', '61.4'], ['98', 'University of Science and Technology of China', 'Asia', '60.8'], ['99', 'Eindhoven University of Technology', 'Europe', '59.8'], ['100', 'Purdue University', 'North America', '59.5'], ['100', 'Sungkyunkwan University (SKKU)', 'Asia', '59.5'], ['100', 'University of California, Davis', 'North America', '59.5'], ['100', 'Washington University in St. Louis', 'North America', '59.5'], ['104', 'KTH Royal Institute of Technology', 'Europe', '59.3'], ['104', 'Trinity College Dublin, The University of Dublin', 'Europe', '59.3'], ['106', 'The Hong Kong Polytechnic University', 'Asia', '59.1'], ['107', 'Yonsei University', 'Asia', '58.9'], ['108', 'University of Geneva', 'Europe', '58.4'], ['109', 'University of Alberta', 'North America', '58.1'], ['110', 'University of Helsinki', 'Europe', '57.9'], ['111', 'Nagoya University', 'Asia', '57.3'], ['112', 'Technical University of Denmark', 'Europe', '57.1'], ['113', 'Universidad Nacional Autónoma de México', '(UNAM)', 'Latin America', '56.8'], ['114', 'The University of Adelaide', 'Oceania', '56.6'], ['115', 'University of Southern California', 'North America', '56.2'], ['116', 'KIT, Karlsruhe Institute of Technology', 'Europe', '55.9'], ['117', 'Uppsala University', 'Europe', '55.8'], ['118', 'Universidade de São Paulo', 'Latin America', '55.5'], ['119', 'Queen Mary University of London', 'Europe', '55.4'], ['120', 'University of Groningen', 'Europe', '55.2'], ['121', 'Humboldt-Universität zu Berlin', 'Europe', '55.1'], ['122', 'Leiden University', 'Europe', '55'], ['122', 'Nanjing University', 'Asia', '55'], ['124', 'Utrecht University', 'Europe', '54.5'], ['125', 'Wageningen University', 'Europe', '54.4'], ['126', 'Kyushu University', 'Asia', '54.1'], ['126', 'University of Maryland, College Park', 'North America', '54.1'], ['128', 'Chalmers University of Technology', 'Europe', '53.6'], ['128', 'Hokkaido University', 'Asia', '53.6'], ['130', 'Freie Universitaet Berlin', 'Europe', '53.4'], ['131', 'Lancaster University', 'Europe', '53'], ['132', 'Pontificia Universidad Católica de Chile (UC)', 'Latin America', '52.9'], ['132', 'University of California, Santa Barbara (UCSB)', 'North America', '52.9'], ['134', 'University of York', 'Europe', '52.4'], ['135', 'University of Oslo', 'Europe', '51.9'], ['136', 'University of Pittsburgh', 'North America', '51.8'], ['137', 'CentraleSupélec', 'Europe', '51.5'], ['138', 'Ghent University', 'Europe', '51.3'], ['139', 'University of Bern', 'Europe', '51.1'], ['140', 'Aalto University', 'Europe', '50.8'], ['141', 'Aarhus University', 'Europe', '50.7'], ['141', 'Michigan State University', 'North America', '50.7'], ['141', 'Newcastle University', 'Europe', '50.7'], ['144', 'RWTH Aachen University', 'Europe', '50.4'], ['145', 'Cardiff University', 'Europe', '50.3'], ['146', 'McMaster University', 'North America', '50.1'], ['147', 'Technische Universität Berlin (TU Berlin)', 'Europe', '49.9'], ['148', 'Emory University', 'North America', '49.6'], ['149', 'Université de Montréal', 'North America', '49.5'], ['149', 'University of Lausanne', 'Europe', '49.5'], ['151', 'Hanyang University', 'Asia', '49.4'], ['153', 'École Normale Supérieure de Lyon', 'Europe', '49.2'], ['154', 'The Hebrew University of Jerusalem', 'Asia', '49.1'], ['154', 'The University of Exeter', 'Europe', '49.1'], ['156', 'Politecnico di Milano', 'Europe', '48.7'], ['156', 'University of Minnesota', 'North America', '48.7'], ['158', 'University of Bath', 'Europe', '48.6'], ['159', 'Universidad Autónoma de Madrid', 'Europe', '48.5'], ['160', 'University of Basel', 'Europe', '48.4'], ['160', 'University of Technology Sydney', 'Oceania', '48.4'], ['162', 'Indian Institute of Technology Bombay (IITB)', 'Asia', '48.2'], ['163', 'National Tsing Hua University', 'Asia', '48'], ['163', 'University of Waterloo', 'North America', '48'], ['165', 'Université catholique de Louvain (UCL)', 'Europe', '47.9'], ['164', 'University of Liverpool', 'Europe', '47.9'], ['166', 'Universitat de Barcelona', 'Europe', '47.8'], ['167', "Scuola Superiore Sant'Anna Pisa di Studi Universitari e di Perfezionamento", 'Europe', '47.7'], ['168', 'Eberhard Karls Universität Tübingen', 'Europe', '47.6'], ['169', 'University of California, Irvine', 'North America', '47.5'], ['170', 'Indian Institute of Science', 'Asia', '47.1'], ['171', 'University of Bergen', 'Europe', '46.8'], ['172', 'Indian Institute of Technology Delhi (IITD)', 'Asia', '46.6'], ['172', 'University of Aberdeen', 'Europe', '46.6'], ['172', 'University of Twente', 'Europe', '46.6'], ['175', 'Scuola Normale Superiore di Pisa', 'Europe', '46.4'], ['175', 'University of Vienna', 'Europe', '46.4'], ['175', 'University of Otago', 'Oceania', '46.4'], ['178', 'Instituto Tecnológico y de Estudios Superiores de Monterrey', 'Latin America', '46.2'], ['179', 'Erasmus University Rotterdam', 'Europe', '46.1'], ['180', 'Queen’s University Belfast', 'Europe', '45.9'], ['180', 'Alma Mater Studiorum - University of Bologna', 'Europe', '45.9'], ['180', 'University of Florida', 'North America', '45.9'], ['183', 'Dartmouth College', 'North America', '45.8'], ['184', 'Universiti Kebangsaan Malaysia (UKM)', 'Asia', '45.5'], ['184', 'University of Rochester', 'North America', '45.5'], ['186', 'Case Western Reserve University', 'North America', '45.4'], ['186', 'Albert-Ludwigs-Universitaet Freiburg', 'Europe', '45.4'], ['188', 'Vrije Universiteit Brussel (VUB)', 'Europe', '45.2'], ['189', 'King Fahd University of Petroleum & Minerals', 'Asia', '45.1'], ['190', 'University of Colorado Boulder', 'North America', '45'], ['191', 'Technische Universität Dresden', 'Europe', '44.9'], ['192', 'University of Virginia', 'North America', '44.8'], ['193', 'Universitat Autònoma de Barcelona', 'Europe', '44.7'], ['193', 'University College Dublin', 'Europe', '44.7'], ['195', 'University of Reading', 'Europe', '44.4'], ['195', 'Vanderbilt University', 'North America', '44.4'], ['197', 'University of Göttingen', 'Europe', '44.3'], ['198', 'Keio University', 'Asia', '44.1'], ['199', 'Vienna University of Technology', 'Europe', '44'], ['200', 'Stockholm University', 'Europe', '43.9'], ['200', 'University of Cape Town', 'Africa', '43.9'], ['202', 'Universiti Putra Malaysia (UPM)', 'Asia', '43.8'], ['203', 'Texas A&M University', 'North America', '43.5'], ['204', 'Radboud University', 'Europe', '43.3'], ['204', 'Universidade Estadual de Campinas (Unicamp)', 'Latin America', '43.3'], ['206', 'Complutense University of Madrid', 'Europe', '43.2'], ['207', 'Universiti Sains Malaysia (USM)', 'Asia', '43'], ['208', 'National Chiao Tung University', 'Asia', '42.6'], ['208', 'Universidad de Chile', 'Latin America', '42.6'], ['208', 'Waseda University', 'Asia', '42.6'], ['211', 'Maastricht University', 'Europe', '42.5'], ['212', 'Arizona State University', 'North America', '42.3'], ['212', 'University of Notre Dame', 'North America', '42.3'], ['214', 'University of Illinois, Chicago (UIC)', 'North America', '42'], ['214', 'The University of Newcastle, Australia (UON)', 'Oceania', '42'], ['214', 'The University of Western Ontario', 'North America', '42'], ['217', 'Sapienza University of Rome', 'Europe', '41.8'], ['218', 'Loughborough University', 'Europe', '41.4'], ['218', 'University of Wollongong', 'Oceania', '41.4'], ['220', 'Al-Farabi Kazakh National University', 'Asia', '41.3'], ['221', 'Sciences Po', 'Europe', '41'], ['221', 'Victoria University of Wellington', 'Oceania', '41'], ['223', 'Universität Hamburg', 'Europe', '40.9'], ['223', 'University of Antwerp', 'Europe', '40.9'], ['223', 'University of Leicester', 'Europe', '40.9'], ['226', 'Georgetown University', 'North America', '40.8'], ['227', 'University of Sussex', 'Europe', '40.7'], ['228', 'Universiti Teknologi Malaysia', 'Asia', '40.5'], ['229', 'University of Calgary', 'North America', '40.4'], ['230', 'Tel Aviv University', 'Asia', '40.3'], ['231', 'King Abdulaziz University (KAU)', 'Asia', '40'], ['231', 'University of Canterbury', 'Oceania', '40'], ['231', 'Vrije Universiteit Amsterdam', 'Europe', '40'], ['234', 'National Cheng Kung University (NCKU)', 'Asia', '39.4'], ['235', 'Saint Petersburg State University', 'Europe', '39.2'], ['236', 'Royal Holloway University of London', 'Europe', '39.1'], ['237', 'American University of Beirut (AUB)', 'Asia', '39'], ['237', 'Tufts University', 'North America', '39'], ['239', "Queen's University at Kingston", 'North America', '38.9'], ['239', 'Universite libre de Bruxelles', 'Europe', '38.9'], ['239', 'Université Paris-Sud', 'Europe', '38.9'], ['242', 'University of Navarra', 'Europe', '38.8'], ['242', 'University of Miami', 'North America', '38.8'], ['244', 'Novosibirsk State University', 'Europe', '38.7'], ['244', 'Queensland University of Technology (QUT)', 'Oceania', '38.7'], ['246', 'The University of Arizona', 'North America', '38.5'], ['247', 'Technion - Israel Institute of Technology', 'Asia', '38.4'], ['248', 'University of Surrey', 'Europe', '38.3'], ['249', 'Università di Padova', 'Europe', '38.2'], ['250', 'Curtin University', 'Oceania', '38'], ['250', 'Macquarie University', 'Oceania', '38'], ['250', 'RMIT University', 'Oceania', '38'], ['253', 'Technische Universität Darmstadt', 'Europe', '37.9'], ['253', 'Universidad Carlos III de Madrid (UC3M)', 'Europe', '37.9'], ['255', 'Rheinische Friedrich-Wilhelms-Universität Bonn', 'Europe', '37.7'], ['256', 'King Saud University', 'Asia', '37.6'], ['257', 'National Taiwan University of Science and Technology (Taiwan Tech)', 'Asia', '37.5'], ['257', 'Wuhan University', 'Asia', '37.5'], ['259', 'University of Massachusetts Amherst', 'North America', '37.3'], ['260', 'National University of Ireland Galway', 'Europe', '37.1'], ['260', 'Universität Stuttgart', 'Europe', '37.1'], ['260', 'University of Tsukuba', 'Asia', '37.1'], ['263', 'Ecole des Ponts ParisTech', 'Europe', '37'], ['264', 'Indian Institute of Technology Madras (IITM)', 'Asia', '36.7'], ['264', 'Kyung Hee University', 'Asia', '36.7'], ['264', 'Simon Fraser University', 'North America', '36.7'], ['264', 'University of South Australia', 'Oceania', '36.7'], ['268', 'University of Strathclyde', 'Europe', '36.6'], ['269', 'University of East Anglia (UEA)', 'Europe', '36.4'], ['269', 'University of Gothenburg', 'Europe', '36.4'], ['271', 'Chulalongkorn University', 'Asia', '36.3'], ['272', 'Universidad de los Andes', 'Latin America', '36.1'], ['272', 'University of Dundee', 'Europe', '36.1'], ['274', 'University of Waikato', 'Oceania', '36'], ['275', 'Universidad Nacional de Colombia', 'Latin America', '35.9'], ['275', 'Universitat Politècnica de Catalunya · BarcelonaTech (UPC)', 'Europe', '35.9'], ['277', 'Hong Kong Baptist University', 'Asia', '35.8'], ['277', 'Tomsk State University', 'Europe', '35.8'], ['279', 'Dalhousie University', 'North America', '35.7'], ['279', 'North Carolina State University', 'North America', '35.7'], ['279', 'Universität Frankfurt am Main', 'Europe', '35.7'], ['279', 'Universität Innsbruck', 'Europe', '35.7'], ['283', 'Indian Institute of Technology Kanpur (IITK)', 'Asia', '35.6'], ['283', 'Rutgers University–New Brunswick', 'North America', '35.6'], ['285', 'Harbin Institute of Technology', 'Asia', '35.3'], ['285', 'University of Turku', 'Europe', '35.3'], ['287', 'University of Tasmania', 'Oceania', '35.2'], ['288', 'SOAS University of London', 'Europe', '35.1'], ['289', 'Université Grenoble-Alpes', 'Europe', '35'], ['289', 'University of Ottawa', 'North America', '35'], ['291', 'Tongji University', 'Asia', '34.9'], ['292', 'Beijing Normal University', 'Asia', '34.8'], ['292', 'National Yang Ming University', 'Asia', '34.8'], ['292', 'Universitas Indonesia', 'Asia', '34.8'], ['295', 'Indian Institute of Technology Kharagpur (IIT-KGP)', 'Asia', '34.7'], ['295', 'Sun Yat-sen University', 'Asia', '34.7'], ['295', 'Université Diderot', 'Paris 7', 'Europe', '34.7'], ['298', 'Universitat Pompeu Fabra', 'Europe', '34.6'], ['299', 'Bauman Moscow State Technical University', 'Europe', '34.5'], ['299', 'Friedrich-Alexander-Universität Erlangen-Nürnberg', 'Europe', '34.5'], ['299', 'Université Paris 1 Panthéon-Sorbonne', 'Europe', '34.5'], ['302', 'Heriot-Watt University', 'Europe', '34.4'], ['302', 'Linköping University', 'Europe', '34.4'], ['302', "University of Hawai'i at Mañoa", 'North America', '34.4'], ['305', 'Ecole Normale Supérieure de Cachan', 'Europe', '34.3'], ['306', 'Birkbeck, University of London', 'Europe', '34.2'], ['306', 'University of Cologne', 'Europe', '34.2'], ['308', 'National Taiwan Normal University', 'Asia', '34.1'], ['309', 'Deakin University', 'Oceania', '34'], ['310', 'Universitat Politècnica de València', 'Europe', '33.7'], ['310', 'The Katz School at Yeshiva University', 'North America', '33.7'], ['312', 'Moscow Institute of Physics and Technology (MIPT / Moscow Phystech)', 'Europe', '33.6'], ['313', 'University at Buffalo SUNY', 'North America', '33.4'], ['313', 'Xi’an Jiaotong University', 'Asia', '33.4'], ['315', 'Gwangju Institute of Science and Technology (GIST)', 'Asia', '33.3'], ['315', 'Khalifa University', 'Asia', '33.3'], ['317', 'Charles University', 'Europe', '33.2'], ['317', 'Lincoln University', 'Oceania', '33.2'], ['319', 'Ewha Womans University', 'Asia', '33.1'], ['319', 'Tilburg University', 'Europe', '33.1'], ['321', 'Hiroshima University', 'Asia', '32.8'], ['321', 'University of Tartu', 'Europe', '32.8'], ['323', 'Indiana University Bloomington', 'North America', '32.7'], ['323', 'Universiti Brunei Darussalam (UBD)', 'Asia', '32.7'], ['325', 'University of Milan', 'Europe', '32.5'], ['326', 'Northeastern University', 'North America', '32.3'], ['326', 'Universität Jena', 'Europe', '32.3'], ['328', 'University of Porto', 'Europe', '32.2'], ['329', 'Griffith University', 'Oceania', '32.1'], ['329', 'National Research Nuclear University MEPhI (Moscow Engineering Physics Institute)', 'Europe', '32.1'], ['329', 'Westfälische Wilhelms-Universität Münster', 'Europe', '32.1'], ['332', 'Brunel University London', 'Europe', '32'], ['332', 'Massey University', 'Oceania', '32'], ['332', 'Qatar University', 'Asia', '32'], ['332', 'University Ulm', 'Europe', '32'], ['336', 'University of California, Santa Cruz', 'North America', '31.9'], ['336', 'University of Jyväskylä', 'Europe', '31.9'], ['338'

In [11]:
#split 
all_data_3=[]
for i in range(len(columns)):
    chunks = re.split('  +', columns[i])
    all_data_3.append(chunks)
print(all_data_3)

[['1', 'Massachusetts Institute of Technology (MIT)', 'North America', '100'], ['2', 'Stanford University', 'North America', '98.6'], ['3', 'Harvard University', 'North America', '98.5'], ['4', 'California Institute of Technology (Caltech)', 'North America', '97.2'], ['5', 'University of Oxford', 'Europe', '96.8'], ['6', 'University of Cambridge', 'Europe', '95.6'], ['7', 'ETH Zurich - Swiss Federal Institute of Technology', 'Europe', '95.3'], ['8', 'Imperial College London', 'Europe', '93.3'], ['9', 'University of Chicago', 'North America', '93.2'], ['10', 'UCL (University College London)', 'Europe', '92.9'], ['11', 'National University of Singapore (NUS)', 'Asia', '92'], ['12', 'Nanyang Technological University, Singapore (NTU)', 'Asia', '91.3'], ['13', 'Princeton University', 'North America', '90.9'], ['14', 'Cornell University', 'North America', '90.5'], ['15', 'Yale University', 'North America', '89.6'], ['16', 'Columbia University', 'North America', '88.5'], ['17', 'Tsinghua University', 'Asia', '87.2'], ['18', 'The University of Edinburgh', 'Europe', '86.9'], ['19', 'University of Pennsylvania', 'North America', '86.5'], ['20', 'University of Michigan', 'North America', '86.4'], ['21', 'Johns Hopkins University', 'North America', '85.9'], ['22', 'EPFL - Ecole Polytechnique Federale de Lausanne', 'Europe', '85.8'], ['23', 'The University of Tokyo', 'Asia', '85.3'], ['24', 'The Australian National University', 'Oceania', '84.4'], ['25', 'The University of Hong Kong', 'Asia', '84.3'], ['26', 'Duke University', 'North America', '83.9'], ['27', 'University of California, Berkeley (UCB)', 'North America', '83.2'], ['28', 'University of Toronto', 'North America', '83'], ['29', 'The University of Manchester', 'Europe', '82.9'], ['30', 'Peking University', 'Asia', '82.6'], ['31', "King's College London", 'Europe', '82.5'], ['32', 'University of California, Los Angeles (UCLA)', 'North America', '81.9'], ['33', 'McGill University', 'North America', '81.7'], ['34', 'Northwestern University', 'North America', '81.5'], ['35', 'Kyoto University', 'Asia', '81.2'], ['36', 'Seoul National University', 'Asia', '80.6'], ['37', 'The Hong Kong University of Science and Technology', 'Asia', '80.5'], ['38', 'London School of Economics and Political Science (LSE)', 'Europe', '80.2'], ['39', 'The University of Melbourne', 'Oceania', '80.1'], ['40', 'KAIST - Korea Advanced Institute of Science & Technology', 'Asia', '78.7'], ['41', 'University of California, San Diego (UCSD)', 'North America', '78.6'], ['42', 'The University of Sydney', 'Oceania', '78.3'], ['43', 'New York University (NYU)', 'North America', '77.7'], ['44', 'Fudan University', 'Asia', '77.6'], ['45', 'The University of New South Wales (UNSW Sydney)', 'Oceania', '77'], ['46', 'Carnegie Mellon University', 'North America', '76.6'], ['47', 'University of British Columbia', 'North America', '75.8'], ['48', 'The University of Queensland', 'Oceania', '75.7'], ['49', 'The Chinese University of Hong Kong (CUHK)', 'Asia', '75.6'], ['50', 'Université PSL', 'Europe', '75.1'], ['51', 'University of Bristol', 'Europe', '74.9'], ['52', 'Delft University of Technology', 'Europe', '73.3'], ['53', 'University of Wisconsin-Madison', 'North America', '73.2'], ['54', 'The University of Warwick', 'Europe', '72.9'], ['55', 'City University of Hong Kong', 'Asia', '72.1'], ['56', 'Brown University', 'North America', '72'], ['57', 'University of Amsterdam', 'Europe', '71.1'], ['58', 'Tokyo Institute of Technology', 'Asia', '71'], ['59', 'Monash University', 'Oceania', '70.4'], ['59', 'Shanghai Jiao Tong University', 'Asia', '70.4'], ['61', 'Technical University of Munich', 'Europe', '70'], ['62', 'Ludwig-Maximilians-Universität München', 'Europe', '69.4'], ['63', 'University of Texas at Austin', 'North America', '68.7'], ['64', 'Ruprecht-Karls-Universität Heidelberg', 'Europe', '68'], ['65', 'Ecole Polytechnique', 'Europe', '67.9'], ['66', 'University of Washington', 'North America', '67.8'], ['67', 'Osaka University', 'Asia', '67.7'], ['68', 'Zhejiang University', 'Asia', '67.5'], ['69', 'Georgia Institute of Technology', 'North America', '67.4'], ['69', 'University of Glasgow', 'Europe', '67.4'], ['71', 'University of Illinois at Urbana-Champaign', 'North America', '67'], ['72', 'National Taiwan University (NTU)', 'Asia', '66.3'], ['73', 'Universidad de Buenos Aires (UBA)', 'Latin America', '66.2'], ['74', 'Durham University', 'Europe', '65.7'], ['75', 'Sorbonne University', 'Europe', '64.8'], ['75', 'The University of Sheffield', 'Europe', '64.8'], ['77', 'Tohoku University', 'Asia', '64.3'], ['78', 'University of Zurich', 'Europe', '63.6'], ['79', 'University of Birmingham', 'Europe', '63.5'], ['79', 'University of Copenhagen', 'Europe', '63.5'], ['81', 'KU Leuven', 'Europe', '63.4'], ['82', 'University of Nottingham', 'Europe', '63.1'], ['83', 'Pohang University of Science And Technology (POSTECH)', 'Asia', '63'], ['83', 'University of North Carolina, Chapel Hill', 'North America', '63'], ['85', 'The University of Auckland', 'Oceania', '62.8'], ['86', 'Korea University', 'Asia', '62.7'], ['87', 'Rice University', 'North America', '62.6'], ['87', 'Universiti Malaya (UM)', 'Asia', '62.6'], ['89', 'The Ohio State University', 'North America', '62.4'], ['90', 'Lomonosov Moscow State University', 'Europe', '62.3'], ['91', 'The University of Western Australia', 'Oceania', '62.2'], ['92', 'Lund University', 'Europe', '62.1'], ['93', 'Boston University', 'North America', '62'], ['93', 'University of Leeds', 'Europe', '62'], ['95', 'Pennsylvania State University', 'North America', '61.9'], ['96', 'University of Southampton', 'Europe', '61.6'], ['97', 'University of St Andrews', 'Europe', '61.4'], ['98', 'University of Science and Technology of China', 'Asia', '60.8'], ['99', 'Eindhoven University of Technology', 'Europe', '59.8'], ['100', 'Purdue University', 'North America', '59.5'], ['100', 'Sungkyunkwan University (SKKU)', 'Asia', '59.5'], ['100', 'University of California, Davis', 'North America', '59.5'], ['100', 'Washington University in St. Louis', 'North America', '59.5'], ['104', 'KTH Royal Institute of Technology', 'Europe', '59.3'], ['104', 'Trinity College Dublin, The University of Dublin', 'Europe', '59.3'], ['106', 'The Hong Kong Polytechnic University', 'Asia', '59.1'], ['107', 'Yonsei University', 'Asia', '58.9'], ['108', 'University of Geneva', 'Europe', '58.4'], ['109', 'University of Alberta', 'North America', '58.1'], ['110', 'University of Helsinki', 'Europe', '57.9'], ['111', 'Nagoya University', 'Asia', '57.3'], ['112', 'Technical University of Denmark', 'Europe', '57.1'], ['113', 'Universidad Nacional Autónoma de México', '(UNAM)', 'Latin America', '56.8'], ['114', 'The University of Adelaide', 'Oceania', '56.6'], ['115', 'University of Southern California', 'North America', '56.2'], ['116', 'KIT, Karlsruhe Institute of Technology', 'Europe', '55.9'], ['117', 'Uppsala University', 'Europe', '55.8'], ['118', 'Universidade de São Paulo', 'Latin America', '55.5'], ['119', 'Queen Mary University of London', 'Europe', '55.4'], ['120', 'University of Groningen', 'Europe', '55.2'], ['121', 'Humboldt-Universität zu Berlin', 'Europe', '55.1'], ['122', 'Leiden University', 'Europe', '55'], ['122', 'Nanjing University', 'Asia', '55'], ['124', 'Utrecht University', 'Europe', '54.5'], ['125', 'Wageningen University', 'Europe', '54.4'], ['126', 'Kyushu University', 'Asia', '54.1'], ['126', 'University of Maryland, College Park', 'North America', '54.1'], ['128', 'Chalmers University of Technology', 'Europe', '53.6'], ['128', 'Hokkaido University', 'Asia', '53.6'], ['130', 'Freie Universitaet Berlin', 'Europe', '53.4'], ['131', 'Lancaster University', 'Europe', '53'], ['132', 'Pontificia Universidad Católica de Chile (UC)', 'Latin America', '52.9'], ['132', 'University of California, Santa Barbara (UCSB)', 'North America', '52.9'], ['134', 'University of York', 'Europe', '52.4'], ['135', 'University of Oslo', 'Europe', '51.9'], ['136', 'University of Pittsburgh', 'North America', '51.8'], ['137', 'CentraleSupélec', 'Europe', '51.5'], ['138', 'Ghent University', 'Europe', '51.3'], ['139', 'University of Bern', 'Europe', '51.1'], ['140', 'Aalto University', 'Europe', '50.8'], ['141', 'Aarhus University', 'Europe', '50.7'], ['141', 'Michigan State University', 'North America', '50.7'], ['141', 'Newcastle University', 'Europe', '50.7'], ['144', 'RWTH Aachen University', 'Europe', '50.4'], ['145', 'Cardiff University', 'Europe', '50.3'], ['146', 'McMaster University', 'North America', '50.1'], ['147', 'Technische Universität Berlin (TU Berlin)', 'Europe', '49.9'], ['148', 'Emory University', 'North America', '49.6'], ['149', 'Université de Montréal', 'North America', '49.5'], ['149', 'University of Lausanne', 'Europe', '49.5'], ['151', 'Hanyang University', 'Asia', '49.4'], ['153', 'École Normale Supérieure de Lyon', 'Europe', '49.2'], ['154', 'The Hebrew University of Jerusalem', 'Asia', '49.1'], ['154', 'The University of Exeter', 'Europe', '49.1'], ['156', 'Politecnico di Milano', 'Europe', '48.7'], ['156', 'University of Minnesota', 'North America', '48.7'], ['158', 'University of Bath', 'Europe', '48.6'], ['159', 'Universidad Autónoma de Madrid', 'Europe', '48.5'], ['160', 'University of Basel', 'Europe', '48.4'], ['160', 'University of Technology Sydney', 'Oceania', '48.4'], ['162', 'Indian Institute of Technology Bombay (IITB)', 'Asia', '48.2'], ['163', 'National Tsing Hua University', 'Asia', '48'], ['163', 'University of Waterloo', 'North America', '48'], ['165', 'Université catholique de Louvain (UCL)', 'Europe', '47.9'], ['164', 'University of Liverpool', 'Europe', '47.9'], ['166', 'Universitat de Barcelona', 'Europe', '47.8'], ['167', "Scuola Superiore Sant'Anna Pisa di Studi Universitari e di Perfezionamento", 'Europe', '47.7'], ['168', 'Eberhard Karls Universität Tübingen', 'Europe', '47.6'], ['169', 'University of California, Irvine', 'North America', '47.5'], ['170', 'Indian Institute of Science', 'Asia', '47.1'], ['171', 'University of Bergen', 'Europe', '46.8'], ['172', 'Indian Institute of Technology Delhi (IITD)', 'Asia', '46.6'], ['172', 'University of Aberdeen', 'Europe', '46.6'], ['172', 'University of Twente', 'Europe', '46.6'], ['175', 'Scuola Normale Superiore di Pisa', 'Europe', '46.4'], ['175', 'University of Vienna', 'Europe', '46.4'], ['175', 'University of Otago', 'Oceania', '46.4'], ['178', 'Instituto Tecnológico y de Estudios Superiores de Monterrey', 'Latin America', '46.2'], ['179', 'Erasmus University Rotterdam', 'Europe', '46.1'], ['180', 'Queen’s University Belfast', 'Europe', '45.9'], ['180', 'Alma Mater Studiorum - University of Bologna', 'Europe', '45.9'], ['180', 'University of Florida', 'North America', '45.9'], ['183', 'Dartmouth College', 'North America', '45.8'], ['184', 'Universiti Kebangsaan Malaysia (UKM)', 'Asia', '45.5'], ['184', 'University of Rochester', 'North America', '45.5'], ['186', 'Case Western Reserve University', 'North America', '45.4'], ['186', 'Albert-Ludwigs-Universitaet Freiburg', 'Europe', '45.4'], ['188', 'Vrije Universiteit Brussel (VUB)', 'Europe', '45.2'], ['189', 'King Fahd University of Petroleum & Minerals', 'Asia', '45.1'], ['190', 'University of Colorado Boulder', 'North America', '45'], ['191', 'Technische Universität Dresden', 'Europe', '44.9'], ['192', 'University of Virginia', 'North America', '44.8'], ['193', 'Universitat Autònoma de Barcelona', 'Europe', '44.7'], ['193', 'University College Dublin', 'Europe', '44.7'], ['195', 'University of Reading', 'Europe', '44.4'], ['195', 'Vanderbilt University', 'North America', '44.4'], ['197', 'University of Göttingen', 'Europe', '44.3'], ['198', 'Keio University', 'Asia', '44.1'], ['199', 'Vienna University of Technology', 'Europe', '44'], ['200', 'Stockholm University', 'Europe', '43.9'], ['200', 'University of Cape Town', 'Africa', '43.9'], ['202', 'Universiti Putra Malaysia (UPM)', 'Asia', '43.8'], ['203', 'Texas A&M University', 'North America', '43.5'], ['204', 'Radboud University', 'Europe', '43.3'], ['204', 'Universidade Estadual de Campinas (Unicamp)', 'Latin America', '43.3'], ['206', 'Complutense University of Madrid', 'Europe', '43.2'], ['207', 'Universiti Sains Malaysia (USM)', 'Asia', '43'], ['208', 'National Chiao Tung University', 'Asia', '42.6'], ['208', 'Universidad de Chile', 'Latin America', '42.6'], ['208', 'Waseda University', 'Asia', '42.6'], ['211', 'Maastricht University', 'Europe', '42.5'], ['212', 'Arizona State University', 'North America', '42.3'], ['212', 'University of Notre Dame', 'North America', '42.3'], ['214', 'University of Illinois, Chicago (UIC)', 'North America', '42'], ['214', 'The University of Newcastle, Australia (UON)', 'Oceania', '42'], ['214', 'The University of Western Ontario', 'North America', '42'], ['217', 'Sapienza University of Rome', 'Europe', '41.8'], ['218', 'Loughborough University', 'Europe', '41.4'], ['218', 'University of Wollongong', 'Oceania', '41.4'], ['220', 'Al-Farabi Kazakh National University', 'Asia', '41.3'], ['221', 'Sciences Po', 'Europe', '41'], ['221', 'Victoria University of Wellington', 'Oceania', '41'], ['223', 'Universität Hamburg', 'Europe', '40.9'], ['223', 'University of Antwerp', 'Europe', '40.9'], ['223', 'University of Leicester', 'Europe', '40.9'], ['226', 'Georgetown University', 'North America', '40.8'], ['227', 'University of Sussex', 'Europe', '40.7'], ['228', 'Universiti Teknologi Malaysia', 'Asia', '40.5'], ['229', 'University of Calgary', 'North America', '40.4'], ['230', 'Tel Aviv University', 'Asia', '40.3'], ['231', 'King Abdulaziz University (KAU)', 'Asia', '40'], ['231', 'University of Canterbury', 'Oceania', '40'], ['231', 'Vrije Universiteit Amsterdam', 'Europe', '40'], ['234', 'National Cheng Kung University (NCKU)', 'Asia', '39.4'], ['235', 'Saint Petersburg State University', 'Europe', '39.2'], ['236', 'Royal Holloway University of London', 'Europe', '39.1'], ['237', 'American University of Beirut (AUB)', 'Asia', '39'], ['237', 'Tufts University', 'North America', '39'], ['239', "Queen's University at Kingston", 'North America', '38.9'], ['239', 'Universite libre de Bruxelles', 'Europe', '38.9'], ['239', 'Université Paris-Sud', 'Europe', '38.9'], ['242', 'University of Navarra', 'Europe', '38.8'], ['242', 'University of Miami', 'North America', '38.8'], ['244', 'Novosibirsk State University', 'Europe', '38.7'], ['244', 'Queensland University of Technology (QUT)', 'Oceania', '38.7'], ['246', 'The University of Arizona', 'North America', '38.5'], ['247', 'Technion - Israel Institute of Technology', 'Asia', '38.4'], ['248', 'University of Surrey', 'Europe', '38.3'], ['249', 'Università di Padova', 'Europe', '38.2'], ['250', 'Curtin University', 'Oceania', '38'], ['250', 'Macquarie University', 'Oceania', '38'], ['250', 'RMIT University', 'Oceania', '38'], ['253', 'Technische Universität Darmstadt', 'Europe', '37.9'], ['253', 'Universidad Carlos III de Madrid (UC3M)', 'Europe', '37.9'], ['255', 'Rheinische Friedrich-Wilhelms-Universität Bonn', 'Europe', '37.7'], ['256', 'King Saud University', 'Asia', '37.6'], ['257', 'National Taiwan University of Science and Technology (Taiwan Tech)', 'Asia', '37.5'], ['257', 'Wuhan University', 'Asia', '37.5'], ['259', 'University of Massachusetts Amherst', 'North America', '37.3'], ['260', 'National University of Ireland Galway', 'Europe', '37.1'], ['260', 'Universität Stuttgart', 'Europe', '37.1'], ['260', 'University of Tsukuba', 'Asia', '37.1'], ['263', 'Ecole des Ponts ParisTech', 'Europe', '37'], ['264', 'Indian Institute of Technology Madras (IITM)', 'Asia', '36.7'], ['264', 'Kyung Hee University', 'Asia', '36.7'], ['264', 'Simon Fraser University', 'North America', '36.7'], ['264', 'University of South Australia', 'Oceania', '36.7'], ['268', 'University of Strathclyde', 'Europe', '36.6'], ['269', 'University of East Anglia (UEA)', 'Europe', '36.4'], ['269', 'University of Gothenburg', 'Europe', '36.4'], ['271', 'Chulalongkorn University', 'Asia', '36.3'], ['272', 'Universidad de los Andes', 'Latin America', '36.1'], ['272', 'University of Dundee', 'Europe', '36.1'], ['274', 'University of Waikato', 'Oceania', '36'], ['275', 'Universidad Nacional de Colombia', 'Latin America', '35.9'], ['275', 'Universitat Politècnica de Catalunya · BarcelonaTech (UPC)', 'Europe', '35.9'], ['277', 'Hong Kong Baptist University', 'Asia', '35.8'], ['277', 'Tomsk State University', 'Europe', '35.8'], ['279', 'Dalhousie University', 'North America', '35.7'], ['279', 'North Carolina State University', 'North America', '35.7'], ['279', 'Universität Frankfurt am Main', 'Europe', '35.7'], ['279', 'Universität Innsbruck', 'Europe', '35.7'], ['283', 'Indian Institute of Technology Kanpur (IITK)', 'Asia', '35.6'], ['283', 'Rutgers University–New Brunswick', 'North America', '35.6'], ['285', 'Harbin Institute of Technology', 'Asia', '35.3'], ['285', 'University of Turku', 'Europe', '35.3'], ['287', 'University of Tasmania', 'Oceania', '35.2'], ['288', 'SOAS University of London', 'Europe', '35.1'], ['289', 'Université Grenoble-Alpes', 'Europe', '35'], ['289', 'University of Ottawa', 'North America', '35'], ['291', 'Tongji University', 'Asia', '34.9'], ['292', 'Beijing Normal University', 'Asia', '34.8'], ['292', 'National Yang Ming University', 'Asia', '34.8'], ['292', 'Universitas Indonesia', 'Asia', '34.8'], ['295', 'Indian Institute of Technology Kharagpur (IIT-KGP)', 'Asia', '34.7'], ['295', 'Sun Yat-sen University', 'Asia', '34.7'], ['295', 'Université Diderot', 'Paris 7', 'Europe', '34.7'], ['298', 'Universitat Pompeu Fabra', 'Europe', '34.6'], ['299', 'Bauman Moscow State Technical University', 'Europe', '34.5'], ['299', 'Friedrich-Alexander-Universität Erlangen-Nürnberg', 'Europe', '34.5'], ['299', 'Université Paris 1 Panthéon-Sorbonne', 'Europe', '34.5'], ['302', 'Heriot-Watt University', 'Europe', '34.4'], ['302', 'Linköping University', 'Europe', '34.4'], ['302', "University of Hawai'i at Mañoa", 'North America', '34.4'], ['305', 'Ecole Normale Supérieure de Cachan', 'Europe', '34.3'], ['306', 'Birkbeck, University of London', 'Europe', '34.2'], ['306', 'University of Cologne', 'Europe', '34.2'], ['308', 'National Taiwan Normal University', 'Asia', '34.1'], ['309', 'Deakin University', 'Oceania', '34'], ['310', 'Universitat Politècnica de València', 'Europe', '33.7'], ['310', 'The Katz School at Yeshiva University', 'North America', '33.7'], ['312', 'Moscow Institute of Physics and Technology (MIPT / Moscow Phystech)', 'Europe', '33.6'], ['313', 'University at Buffalo SUNY', 'North America', '33.4'], ['313', 'Xi’an Jiaotong University', 'Asia', '33.4'], ['315', 'Gwangju Institute of Science and Technology (GIST)', 'Asia', '33.3'], ['315', 'Khalifa University', 'Asia', '33.3'], ['317', 'Charles University', 'Europe', '33.2'], ['317', 'Lincoln University', 'Oceania', '33.2'], ['319', 'Ewha Womans University', 'Asia', '33.1'], ['319', 'Tilburg University', 'Europe', '33.1'], ['321', 'Hiroshima University', 'Asia', '32.8'], ['321', 'University of Tartu', 'Europe', '32.8'], ['323', 'Indiana University Bloomington', 'North America', '32.7'], ['323', 'Universiti Brunei Darussalam (UBD)', 'Asia', '32.7'], ['325', 'University of Milan', 'Europe', '32.5'], ['326', 'Northeastern University', 'North America', '32.3'], ['326', 'Universität Jena', 'Europe', '32.3'], ['328', 'University of Porto', 'Europe', '32.2'], ['329', 'Griffith University', 'Oceania', '32.1'], ['329', 'National Research Nuclear University MEPhI (Moscow Engineering Physics Institute)', 'Europe', '32.1'], ['329', 'Westfälische Wilhelms-Universität Münster', 'Europe', '32.1'], ['332', 'Brunel University London', 'Europe', '32'], ['332', 'Massey University', 'Oceania', '32'], ['332', 'Qatar University', 'Asia', '32'], ['332', 'University Ulm', 'Europe', '32'], ['336', 'University of California, Santa Cruz', 'North America', '31.9'], ['336', 'University of Jyväskylä', 'Europe', '31.9'], ['338'

In [12]:
#extracting features:rank,name,area
ranks=[]
names=[]
areas=[]
for data in all_data_3:
    ranks.append(data[0])
    names.append(data[1])
    areas.append(data[2])


data_3={
    'UNI_RANKS':ranks,
    'UNI_NAMES':names,
    'UNI_AREAS':areas
}

d3=pd.DataFrame(data_3,index=None)
d3

,UNI_RANKS,UNI_NAMES,UNI_AREAS
0,1,Massachusetts Institute of Technology (MIT),North America
1,2,Stanford University,North America
2,3,Harvard University,North America
3,4,California Institute of Technology (Caltech),North America
4,5,University of Oxford,Europe
...,...,...,...
1995,801-1000,Voronezh State University,Europe
1996,801-1000,Vytautas Magnus University,Europe
1997,801-1000,Universitatea de Vest din Timisoara /,West University of Timisoara
1998,801-1000,Wroclaw University of Science and Technology (...,Europe
1999,801-1000,Yeungnam University,Asia

In [13]:
#merge all datasets to the BIK
dataset_all = pd.concat([bik,dataset_1_new, dataset_2_new,d3], axis=1)
dataset_all

,Unnamed: 0,Authors,Title,Citation,DOI,Year,Month,0,1,2,...,NAME,ADDRESS,STATE,COUNTRY,COUNTY,SOURCE,WEBSITE,UNI_RANKS,UNI_NAMES,UNI_AREAS
0,0.0,"Inka Regine Weingaertner, Sarah Koutnik, Herma...",Rounak Nassirpour,"PLOS One, January 2013 | Volume 8 | Issue 1 | ...",10.1371/journal.pone.0053510,2013.0,1-Jan,1.0,NaN,1.0,...,BRYANT & STRATTON COLLEGE-AMHERST,3650 MILLERSPORT HIGHWAY,NY,USA,ERIE,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,https://www.bryantstratton.edu,1,Massachusetts Institute of Technology (MIT),North America
1,1.0,"Jessica M. Esparza, Eileen OÅToole, Linya Li,...",Katanin Localization Requires Triplet Microtub...,"PLOS ONE, January 2013 | Volume 8 | Issue 1 | ...",10.1371/journal.pone.0053940,2013.0,1-Jan,NaN,1.0,NaN,...,CUNY SCHOOL OF LAW,2 COURT SQUARE,NY,USA,QUEENS,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.law.cuny.edu,2,Stanford University,North America
2,2.0,"Sreedevi Avasarala, Fangfang Zhang, Guangliang...",Curcumin Modulates the Inflammatory Response a...,"PLOS ONE, February 2013 | Volume 8 | Issue 2 |...",10.1371/journal.pone.0057285,2013.0,2-Feb,NaN,NaN,1.0,...,ROCKLAND COMMUNITY COLLEGE,145 COLLEGE RD,NY,USA,ROCKLAND,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.sunyrockland.edu/,3,Harvard University,North America
3,3.0,"Rounak Nassirpour, Pramod P. Mehta, Sangita M....",miR-221 Promotes Tumorigenesis in Human Triple...,"PLOS ONE, April 2013 | Volume 8 | Issue 4 | e6...",10.1371/journal.pone.0062170,2013.0,04April,1.0,NaN,NaN,...,SOUTHERN WESTCHESTER BOCES-PRACTICAL NURSING P...,450 MAMARONECK AVENUE,NY,USA,WESTCHESTER,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.swboces.org,4,California Institute of Technology (Caltech),North America
4,4.0,"Jianuo Liu, Peng Xu, Cory Collins, Han Liu, J...",HIV-1 Tat Protein Increases Microglial Outward...,"PLOS ONE, May 2013 | Volume 8 | Issue 5 | e649...",10.1371/journal.pone.0064904,2013.0,5-May,NaN,1.0,NaN,...,OHIO VALLEY COLLEGE OF TECHNOLOGY,15258 STATE ROUTE 170,OH,USA,COLUMBIANA,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,ovct.edu,5,University of Oxford,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,BAKER COLLEGE - FLINT,1050 WEST BRISTOL ROAD,MI,USA,GENESEE,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,NOT AVAILABLE,NaN,NaN,NaN
6555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,WELLSPRING SCHOOL OF ALLIED HEALTH-WICHITA,"650 N CARRIAGE PARKWAY, STE 55",KS,USA,SEDGWICK,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.wellspring.edu,NaN,NaN,NaN
6556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,ACCESS CAREERS-ISLANDIA,"1930 VETERANS HIGHWAY, SUITE 10",NY,USA,SUFFOLK,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.accesscareers.net,NaN,NaN,NaN
6557,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,FRANCISCAN SCHOOL OF THEOLOGY - SAN DIEGO,5998 ALCALA PARK,CA,USA,SAN DIEGO,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,NOT AVAILABLE,NaN,NaN,NaN
6558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,UNIVERSITY OF MONTANA (THE) - BITTERROOT COLLE...,103 SOUTH 9TH STREET,MT,USA,RAVALLI,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,NOT AVAILABLE,NaN,NaN,NaN

In [14]:
dataset = dataset_all.iloc[:214]
dataset

,Unnamed: 0,Authors,Title,Citation,DOI,Year,Month,0,1,2,...,NAME,ADDRESS,STATE,COUNTRY,COUNTY,SOURCE,WEBSITE,UNI_RANKS,UNI_NAMES,UNI_AREAS
0,0.0,"Inka Regine Weingaertner, Sarah Koutnik, Herma...",Rounak Nassirpour,"PLOS One, January 2013 | Volume 8 | Issue 1 | ...",10.1371/journal.pone.0053510,2013.0,1-Jan,1.0,NaN,1.0,...,BRYANT & STRATTON COLLEGE-AMHERST,3650 MILLERSPORT HIGHWAY,NY,USA,ERIE,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,https://www.bryantstratton.edu,1,Massachusetts Institute of Technology (MIT),North America
1,1.0,"Jessica M. Esparza, Eileen OÅToole, Linya Li,...",Katanin Localization Requires Triplet Microtub...,"PLOS ONE, January 2013 | Volume 8 | Issue 1 | ...",10.1371/journal.pone.0053940,2013.0,1-Jan,NaN,1.0,NaN,...,CUNY SCHOOL OF LAW,2 COURT SQUARE,NY,USA,QUEENS,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.law.cuny.edu,2,Stanford University,North America
2,2.0,"Sreedevi Avasarala, Fangfang Zhang, Guangliang...",Curcumin Modulates the Inflammatory Response a...,"PLOS ONE, February 2013 | Volume 8 | Issue 2 |...",10.1371/journal.pone.0057285,2013.0,2-Feb,NaN,NaN,1.0,...,ROCKLAND COMMUNITY COLLEGE,145 COLLEGE RD,NY,USA,ROCKLAND,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.sunyrockland.edu/,3,Harvard University,North America
3,3.0,"Rounak Nassirpour, Pramod P. Mehta, Sangita M....",miR-221 Promotes Tumorigenesis in Human Triple...,"PLOS ONE, April 2013 | Volume 8 | Issue 4 | e6...",10.1371/journal.pone.0062170,2013.0,04April,1.0,NaN,NaN,...,SOUTHERN WESTCHESTER BOCES-PRACTICAL NURSING P...,450 MAMARONECK AVENUE,NY,USA,WESTCHESTER,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.swboces.org,4,California Institute of Technology (Caltech),North America
4,4.0,"Jianuo Liu, Peng Xu, Cory Collins, Han Liu, J...",HIV-1 Tat Protein Increases Microglial Outward...,"PLOS ONE, May 2013 | Volume 8 | Issue 5 | e649...",10.1371/journal.pone.0064904,2013.0,5-May,NaN,1.0,NaN,...,OHIO VALLEY COLLEGE OF TECHNOLOGY,15258 STATE ROUTE 170,OH,USA,COLUMBIANA,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,ovct.edu,5,University of Oxford,Europe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209,209.0,"Nathalie Delgehyr, Uta Wieland, He_lÅ¹ne Rango...","Drosophila Mgr, a Prefoldin subunit cooperatin...","PNAS | April 10, 2012 | vol. 109 | no. 15 | 57...",10.1073/pnas.1108537109,2012.0,NaN,NaN,1.0,NaN,...,CONCORDE CAREER COLLEGE-SAN DIEGO,"4393 IMPERIAL AVENUE, SUITE 100",CA,USA,SAN DIEGO,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,https://www.concorde.edu/campus/san-diego-cali...,208,Waseda University,Asia
210,210.0,"Rajesh K. Grover, Julong Cheng, Yingjie Peng, ...",The costimulatory immunogen LPS induces the B-...,"PNAS _ April 17, 2012 _ vol. 109 _ no. 16, 603...",10.1073/pnas.1202214109,2012.0,NaN,NaN,1.0,NaN,...,PALO ALTO UNIVERSITY,1791 ARASTRADERO RD,CA,USA,SANTA CLARA,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.paloaltou.edu,211,Maastricht University,Europe
211,211.0,"Kevin Y. Lee, Yuji Yamamoto, Jeremie Boucher, ...",Shox2 is a molecular determinant of depot-spec...,"PNAS | July 9, 2013 | vol. 110 | no. 28 | 1140...",10.1073/pnas.1310331110,2013.0,NaN,NaN,1.0,NaN,...,EMILY GRIFFITH TECHNICAL COLLEGE,1860 LINCOLN STREET,CO,USA,DENVER,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.emilygriffith.edu,212,Arizona State University,North America
212,212.0,"Shuyu Ren, Bryce G. Johnson, Yujiro Kida, Coli...",LRP-6 is a coreceptor for multiple fibrogenic ...,"PNAS | January22,2013 | vol.110 | no.4 | 1441",10.1073/pnas.1211179110,2013.0,NaN,NaN,NaN,1.0,...,SAMUEL MERRITT UNIVERSITY,3100 TELEGRAPH AVENUE,CA,USA,ALAMEDA,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.samuelmerritt.edu,212,University of Notre Dame,North America
213,213.0,"Zhongyuan Wang, Yanping Wu, Haifeng Wang, Yang...",Interplay of mevalonate and Hippo pathways reg...,"PNAS | Published online December 23, 2013 | E8...",10.1073/pnas.1319190110,2014.0,NaN,NaN,NaN,1.0,...,GA BEAUTY & BARBER SCHOOL,3301 NORTH WARE ROAD SUITE A,TX,USA,HIDALGO,https://nces.ed.gov/GLOBALLOCATOR/col_info_pop...,www.ganailsbeauty.com,214,"University of Illinois, Chicago (UIC)",North America

In [15]:
dataset.to_csv('updated_bik_with_features.csv')